version: '2'

services:
  redis:
    image: 'redis:3.2-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  myapp:
    tty: true # Enables debugging capabilities when attached to this container.
    image: 'bitnami/rails:latest'
    environment:
      - DATABASE_HOST=mariadb
      - DATABASE_NAME=my_app_development
      - ENCRYPTION_KEY=7PJMdbdaFqa4Wz+m99kWrbOoNtcG28C=
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - mariadb
    ports:
      - 3000:3000
    volumes:
      - .:/app

  sidekiq:
    tty: true # Enables debugging capabilities when attached to this container.
    image: 'bitnami/rails:latest'
    environment:
      - SKIP_DB_SETUP=true
      - DATABASE_HOST=mariadb
      - DATABASE_NAME=my_app_development
      - ENCRYPTION_KEY=7PJMdbdaFqa4Wz+m99kWrbOoNtcG28C=
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - myapp
      - redis
    command: bundle exec sidekiq
    volumes:
      - '.:/app'

volumes:
  redis:
